export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCES="GET_CATEGORIES_SUCCES"

export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"



//REDUXTA KULLANILAN YARDIMCI DOSYA
//aksiyonları yazıyoruz 